# Generated by Django 5.1.15 on 2026-06-09 07:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='카메라 명')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='설치 위치')),
                ('stream_url', models.CharField(blank=True, default='0', help_text='0 = 로컬 웹캠, 또는 RTSP/HTTP URL', max_length=300, verbose_name='스트림 URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='운영 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '카메라',
                'verbose_name_plural': '카메라',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DetectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('upload', '이미지 업로드'), ('live', '실시간 스트림'), ('api', '외부 API')], default='upload', max_length=20, verbose_name='소스')),
                ('original_image', models.ImageField(upload_to='originals/%Y/%m/%d/', verbose_name='원본')),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='results/%Y/%m/%d/', verbose_name='결과')),
                ('n_total', models.PositiveIntegerField(default=0, verbose_name='탐지 객체 수')),
                ('n_violation', models.PositiveIntegerField(default=0, verbose_name='위반 수')),
                ('mean_conf', models.FloatField(default=0.0, verbose_name='평균 신뢰도')),
                ('elapsed_ms', models.FloatField(default=0.0, verbose_name='처리 시간(ms)')),
                ('enhance_applied', models.BooleanField(default=False, verbose_name='Zero-DCE++ 적용')),
                ('sr_applied_count', models.PositiveIntegerField(default=0, verbose_name='SR 적용 ROI 수')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='발생 시각')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='safety.camera', verbose_name='카메라')),
            ],
            options={
                'verbose_name': '탐지 이벤트',
                'verbose_name_plural': '탐지 이벤트',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ViolationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('OK', '정상'), ('NO_HELMET', '미착용'), ('INCORRECT_WEAR', '올바르지 않은 착용')], max_length=20, verbose_name='판정')),
                ('yolo_class', models.CharField(blank=True, max_length=40, verbose_name='YOLO 클래스')),
                ('yolo_score', models.FloatField(default=0.0, verbose_name='YOLO 신뢰도')),
                ('cls_presence', models.FloatField(default=0.0, verbose_name='착용 확률')),
                ('cls_correct', models.FloatField(default=0.0, verbose_name='올바른 착용 확률')),
                ('bbox_x1', models.IntegerField()),
                ('bbox_y1', models.IntegerField()),
                ('bbox_x2', models.IntegerField()),
                ('bbox_y2', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='safety.detectionevent', verbose_name='이벤트')),
            ],
            options={
                'verbose_name': '위반 로그',
                'verbose_name_plural': '위반 로그',
                'ordering': ['-created_at'],
            },
        ),
    ]
