# Generated by Django 5.1.15 on 2026-06-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='video_file',
            field=models.FileField(blank=True, help_text='mp4/avi 등 시연용 영상을 업로드하면 이 파일이 우선 사용됩니다.', null=True, upload_to='cameras/', verbose_name='영상 파일 (선택)'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='stream_url',
            field=models.CharField(blank=True, default='', help_text='0 = 로컬 웹캠, 또는 RTSP/HTTP URL. 파일을 업로드하면 이 값은 무시됩니다.', max_length=300, verbose_name='스트림 URL (선택)'),
        ),
    ]
