# Generated by Django 5.2.15 on 2026-06-12 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='xray/', verbose_name='X-ray 영상')),
                ('captured_at', models.DateTimeField(auto_now_add=True, verbose_name='촬영시각')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='촬영 위치')),
                ('clinical_note', models.TextField(blank=True, verbose_name='임상 메모')),
                ('status', models.CharField(choices=[('uploaded', '업로드 완료'), ('ai_analyzed', 'AI 분석 완료'), ('under_review', '전문의 검토 중'), ('confirmed', '전문의 확정'), ('archived', '보관')], default='uploaded', max_length=20, verbose_name='상태')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='patients.patient')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='studies_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '검사',
                'verbose_name_plural': '검사',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predictions_json', models.TextField()),
                ('positive_findings_json', models.TextField()),
                ('top_finding', models.CharField(blank=True, max_length=40)),
                ('top_prob', models.FloatField(default=0.0)),
                ('threshold', models.FloatField(default=0.5)),
                ('inference_ms', models.IntegerField(default=0)),
                ('gradcam', models.ImageField(blank=True, null=True, upload_to='gradcam/')),
                ('gradcam_class', models.CharField(blank=True, max_length=40)),
                ('is_demo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('final_findings_json', models.TextField(blank=True, default='')),
                ('radiologist_note', models.TextField(blank=True)),
                ('severity', models.CharField(blank=True, choices=[('mild', '경증'), ('moderate', '중등도'), ('severe', '중증'), ('critical', '위중')], max_length=10)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses_confirmed', to=settings.AUTH_USER_MODEL)),
                ('study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='studies.study')),
            ],
            options={
                'verbose_name': 'AI 판독',
                'verbose_name_plural': 'AI 판독',
            },
        ),
    ]
