# Generated by Django 5.2.15 on 2026-06-12 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_code', models.CharField(max_length=30, unique=True, verbose_name='환자코드')),
                ('name', models.CharField(max_length=80, verbose_name='이름')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('sex', models.CharField(blank=True, choices=[('M', '남'), ('F', '여')], max_length=1, verbose_name='성별')),
                ('guardian_phone', models.CharField(blank=True, max_length=20, verbose_name='보호자 연락처')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_registered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '환자',
                'verbose_name_plural': '환자',
                'ordering': ['-created_at'],
            },
        ),
    ]
