# Generated by Django 4.2.30 on 2026-06-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(blank=True, max_length=64, verbose_name='이름/식별자')),
                ('body_part', models.CharField(choices=[('heart', '심음'), ('lung', '폐음')], default='lung', max_length=8, verbose_name='측정 부위')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시각')),
                ('original_wav', models.FileField(upload_to='uploads/', verbose_name='원본(LR) 측정본')),
                ('restored_wav', models.FileField(blank=True, null=True, upload_to='restored/', verbose_name='SR 복원본')),
                ('predicted_label', models.CharField(blank=True, choices=[('normal', '정상'), ('crackle', '수포음 (Crackle)'), ('wheeze', '천명음 (Wheeze)'), ('both', '수포음+천명음 동반'), ('', '미진단')], default='', max_length=16, verbose_name='진단 라벨')),
                ('confidence', models.FloatField(default=0.0, verbose_name='Top-1 확신도')),
                ('probabilities', models.JSONField(blank=True, default=dict, verbose_name='클래스별 확률')),
                ('snr_in_db', models.FloatField(blank=True, null=True, verbose_name='입력 SNR(dB)')),
                ('snr_out_db', models.FloatField(blank=True, null=True, verbose_name='복원 SNR(dB)')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리 완료 시각')),
                ('error', models.TextField(blank=True, verbose_name='오류 메시지')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
