# Generated by Django 4.2.30 on 2026-06-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='spectrogram_png',
            field=models.FileField(blank=True, null=True, upload_to='visuals/', verbose_name='스펙트로그램 비교'),
        ),
        migrations.AddField(
            model_name='recording',
            name='spectrum_png',
            field=models.FileField(blank=True, null=True, upload_to='visuals/', verbose_name='평균 스펙트럼'),
        ),
        migrations.AddField(
            model_name='recording',
            name='waveform_png',
            field=models.FileField(blank=True, null=True, upload_to='visuals/', verbose_name='파형 비교'),
        ),
    ]
